apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs
  template:
    metadata:
      labels:
        app: nodejs
    spec:
      containers:
      - name: nodejs-container
        image: edencoania/release:nodejs
        ports:
        - containerPort: 8000
        env:
        - name: BASE_URL
          value: "http://nodejs-service"
