apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-app
spec:
  replicas: 1 # Adjust the number of replicas as needed
  selector:
    matchLabels:
      app: react-app
  template:
    metadata:
      labels:
        app: react-app
    spec:
      containers:
      - name: react-app
        image: edencoania/release:bob # Replace with your Docker image name and tag
        imagePullPolicy: Always
        ports:
        - containerPort: 3000 # Port your React app listens on
        env:
        - name: REACT_APP_BASE_URL
          value: "http://nodejs-service" # DNS name of your Node.js service
