apiVersion: v1
kind: Service
metadata:
  name: react-app-service
spec:
  selector:
    app: react-app
  ports:
  - protocol: TCP
    port: 3000 # Port exposed by the service
    targetPort: 80 # Port your React app listens on inside the container
    nodePort: 30000 # You can choose any available port number
  type: NodePort # Change to NodePort or ClusterIP if LoadBalancer is not supported
